'vapor build' unable to link dependencies
It's nothing much, but might be useful for beginners who want to try server-side swift

Log : 
vapor build
warning: refname '0.1.1' is ambiguous.
warning: refname '0.1.1' is ambiguous.
Resolved version: 0.1.1
warning: refname '0.4.0' is ambiguous.
warning: refname '0.4.0' is ambiguous.
Resolved version: 0.4.0
error: The dependency graph could not be satisfied (https://github.com/qutheory/vapor.git)

Works when .Package line changed to minor: 4 : 
Resolved version: 0.4.0
Resolved version: 0.6.1